name: flutter_flatpak
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.19.0-83.0.dev <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  args: ^2.3.1
  fhir_yaml: ^0.9.0
  pubspec: ^2.3.0
  yaml: ^3.1.1
  yaml_writer: ^1.0.2
